imports:
    - { resource: easyadmin/ }

easy_admin:
    user:
        display_name: true
        name_property_path: 'username'

    site_name: 'Panneau de configuration du site'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { label: 'Retour à la page accueil', route: 'homepage' }
            - { entity: 'Introduction',label: 'présentation du site' ,icon: 'book' }
            - { entity: 'Event',label: 'évènements' ,icon: 'book' }
            - { entity: 'Team',label: 'équipe' ,icon: 'book' }
            - { entity: 'Partner', label: 'Nos partenaires', icon: 'book'}
            - { entity: 'Action',label: 'actions' ,icon: 'book' }
            - { entity: 'Galery',label: 'images' ,icon: 'book' }
            - { entity: 'Multimedia',label: 'vidéos' ,icon: 'book' }
    entities:
       # List the entity class name you want to manage
        - App\Entity\Multimedia
