vich_uploader:
    db_driver: orm

    mappings:
        Action:
            uri_prefix: public/images_action
            upload_destination: '%kernel.project_dir%/public/images_action'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        Event:
            uri_prefix: public/images_event
            upload_destination: '%kernel.project_dir%/public/images_event'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        Galery:
            uri_prefix: public/galery
            upload_destination: '%kernel.project_dir%/public/galery'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        Introduction:
            uri_prefix: public/images_introduction
            upload_destination: '%kernel.project_dir%/public/images_action'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true