easy_admin:
    entities:
        Action:
            class: App\Entity\Action
            form:
                fields:
                    - { property: 'title', label: 'Titre'}
                    - { property: 'content', type: 'fos_ckeditor', label: 'Contenu' }
                    - { property: 'imageFile', type: 'vich_image', label: 'image'}
                    - { property: 'updatedAt',type: 'datetime', label: 'date de mise en ligne'}
