#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

# config/routes/easy_admin.yaml
easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
